// Copyright 2024-2026 Alişah Özcan
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// CKKS ring switching between two power-of-two rings sharing an RNS chain.
//
// This is item 5 of LLAMA3_8B_LAYER_FLOW.md §10 — the subsystem the two-ring
// Llama-3 flow was blocked on: run the nonlinear layers at the big ring
// (logN = 16, where the level budget lives), run Algorithm 5's rectangular
// PCMM at the small ring (logN = 12/13, the only place its N/2 − 1 Galois
// keys fit), and cross between them at zero multiplicative levels.
//
// The construction is Sylph's (arXiv 2601.18511 §3.3), reinterpreted through
// the module decomposition R_N = ⊕_{j<k} X^j · R_{N'}[X^k], k = N/N':
//
//   DOWN   ct_big under sk_big
//            → keyswitch to s'(X^k)        (s' the small-ring secret,
//                                           embedded in R_N by placing its
//                                           coefficient j at X^{j·k})
//            → INTT (big tables) → stride-k coefficient split
//            → k small ciphertexts (a_j, b_j), each ALREADY a valid
//              encryption of m_j under s' in R_{N'} — exactly, with no new
//              noise, because b_j + a_j·s' picks out the coefficients of
//              b + a·s'(X^k) in the residue class j mod k.
//            → forward NTT with the small context's tables.
//
//   UP     the mirror: gather → batched small INTT → interleave
//            → big NTT → ciphertext under s'(X^k) → keyswitch to sk_big.
//
// Each direction costs exactly ONE key switch and ZERO levels. The split and
// interleave are index moves; all the noise lives in the key switch, which is
// the library's ordinary switchkey pipeline with an ordinary Switchkey.
//
// What makes this work without any cross-ring key machinery: the embedded
// secret s'(X^k) is materialised as a big-ring Secretkey through the explicit
// coefficient constructor, so both switch keys are in-context keys of the BIG
// context, generated by the existing HEKeyGenerator::generate_switch_key.
// The small context never sees a key switch at all — the split ciphertexts
// are valid under s' by construction.
//
// The two contexts must be built to share their primes: the small context
// takes the big chain's bottom-prefix Q values verbatim through
// set_coeff_modulus_values (primes generated ≡ 1 mod 2N are automatically
// NTT-friendly at every smaller power-of-two ring). Levels then correspond by
// active-prime count: a big ciphertext with l active primes maps to small
// ciphertexts at depth (Q_small − l), and back. Rescales taken inside the
// small-ring island divide by the SAME prime value the big ring would have
// divided by, so scales track across the switch with no correction.
//
// What this deliberately does not do: touch encodings. A switch preserves
// the plaintext polynomial coefficients exactly, so a RECT/SinC-encoded big
// ciphertext descends to the k column polynomials its coefficients already
// interleave — the layout contract of LLAMA3_8B_LAYER_FLOW.md §8 — and the
// encoding_ tag is carried through unchanged.

#ifndef HEONGPU_CKKS_RINGSWITCH_H
#define HEONGPU_CKKS_RINGSWITCH_H

#include <heongpu/host/ckks/context.cuh>
#include <heongpu/host/ckks/ciphertext.cuh>
#include <heongpu/host/ckks/secretkey.cuh>
#include <heongpu/host/ckks/evaluationkey.cuh>
#include <heongpu/host/ckks/keygenerator.cuh>
#include <heongpu/host/ckks/operator.cuh>

#include <memory>
#include <vector>

namespace heongpu
{
    template <> class HERingSwitchOperator<Scheme::CKKS>
    {
      public:
        /**
         * @brief Bind a big and a small CKKS context for ring switching.
         *
         * Requirements, all checked here:
         *   - both contexts generated, n_big a proper multiple of n_small;
         *   - the small context's Q chain is a value-identical prefix of the
         *     big context's Q chain (build the small context with
         *     set_coeff_modulus_values on the big chain's leading values).
         *
         * The special (P) primes of the two contexts are independent: each
         * context key-switches only with its own P. The ring-switch key
         * switches run in the BIG context, so the big context's P count and
         * keyswitching method are the ones that matter for switch quality —
         * at logN = 16 that means at least two special primes (method II);
         * a single special prime has no noise budget there.
         */
        HERingSwitchOperator(HEContext<Scheme::CKKS>& big_context,
                             HEContext<Scheme::CKKS>& small_context);

        /** @brief N_big / N_small. */
        int k() const noexcept { return k_; }

        /** @brief log2(k). */
        int k_power() const noexcept { return k_power_; }

        /** @brief Number of Q primes the two chains share. */
        int shared_prime_count() const noexcept { return small_q_size_; }

        /**
         * @brief The small-ring secret in every form the two rings need.
         *
         * One host-side ternary vector is the source of truth; the two
         * Secretkey objects are built from it because Secretkey stores only
         * NTT-domain RNS residues and cannot be read back.
         */
        struct SecretPair
        {
            /// Ternary coefficients of s', length n_small.
            std::vector<int> coefficients;
            /// s' as a small-context secret key (decrypts the split
            /// ciphertexts; generates the small ring's own Galois/relin keys).
            Secretkey<Scheme::CKKS> small;
            /// s'(X^k) as a big-context secret key (the key-switch target of
            /// DOWN and source of UP).
            Secretkey<Scheme::CKKS> embedded;
        };

        /**
         * @brief Sample a fresh small-ring ternary secret of the given
         * Hamming weight and materialise it in both rings.
         *
         * Deterministic in @p seed, so a fixture can rebuild the same pair.
         */
        SecretPair make_secret_pair(int hamming_weight,
                                    unsigned long long seed) const;

        /** @brief Materialise a caller-supplied ternary secret in both rings. */
        SecretPair make_secret_pair(const std::vector<int>& coefficients) const;

        /**
         * @brief Generate the two switch keys, both in the big context.
         *
         * swk_down transports sk_big → s'(X^k); swk_up transports
         * s'(X^k) → sk_big. @p keygen must belong to the big context and
         * @p embedded must be the SecretPair's embedded key.
         */
        void generate_keys(HEKeyGenerator<Scheme::CKKS>& keygen,
                           Secretkey<Scheme::CKKS>& sk_big,
                           Secretkey<Scheme::CKKS>& embedded);

        bool keys_generated() const noexcept
        {
            return swk_down_ != nullptr && swk_up_ != nullptr;
        }

        /**
         * @brief Ring switch DOWN: one big-ring ciphertext → k small-ring
         * ciphertexts. One key switch, zero levels.
         *
         * @param input Big-ring ciphertext under sk_big, NTT domain, with no
         *              pending rescale/relinearisation, whose active prime
         *              count l satisfies l ≤ shared_prime_count().
         * @param big_operators Operator of the BIG context (performs the key
         *              switch with swk_down).
         * @return k ciphertexts of the small context at depth
         *              (Q_small − l), valid under the SecretPair's small key,
         *              scale/encoding carried through unchanged.
         */
        std::vector<Ciphertext<Scheme::CKKS>>
        switch_down(Ciphertext<Scheme::CKKS>& input,
                    HEArithmeticOperator<Scheme::CKKS>& big_operators,
                    const ExecutionOptions& options = ExecutionOptions());

        /**
         * @brief Ring switch UP: k small-ring ciphertexts → one big-ring
         * ciphertext under sk_big. One key switch, zero levels.
         *
         * All k inputs must sit at one level with one scale. The composed
         * plaintext is m(X) = Σ_j m_j(X^k)·X^j — the exact inverse of
         * switch_down's split, so up(down(ct)) is the identity up to the two
         * key switches' noise.
         */
        Ciphertext<Scheme::CKKS>
        compose_up(std::vector<Ciphertext<Scheme::CKKS>>& inputs,
                   HEArithmeticOperator<Scheme::CKKS>& big_operators,
                   const ExecutionOptions& options = ExecutionOptions());

        /**
         * @brief The keyswitch-free half of DOWN, public for profiling and
         * for callers that already hold a ciphertext under s'(X^k).
         */
        std::vector<Ciphertext<Scheme::CKKS>>
        split_embedded(const Ciphertext<Scheme::CKKS>& input,
                       const ExecutionOptions& options = ExecutionOptions());

        /**
         * @brief The keyswitch-free half of UP: the composed ciphertext is
         * returned still under s'(X^k).
         */
        Ciphertext<Scheme::CKKS>
        interleave_embedded(const std::vector<Ciphertext<Scheme::CKKS>>& inputs,
                            const ExecutionOptions& options =
                                ExecutionOptions());

      private:
        /// Stamp a ciphertext of `ctx` at the level holding `limbs` active
        /// primes, metadata copied from `like`, with NO device buffer. Used
        /// for keyswitch outputs: the switchkey pipeline installs its own
        /// right-sized buffer via memory_set, so pre-allocating one is waste.
        Ciphertext<Scheme::CKKS>
        metadata_at_level(const HEContext<Scheme::CKKS>& ctx, int limbs,
                          const Ciphertext<Scheme::CKKS>& like) const;

        /// metadata_at_level plus an uninitialised device buffer of
        /// 2·limbs·n words, allocated stream-ordered on `stream` — the same
        /// stream every kernel that touches it runs on.
        Ciphertext<Scheme::CKKS>
        allocate_at_level(const HEContext<Scheme::CKKS>& ctx, int limbs,
                          const Ciphertext<Scheme::CKKS>& like,
                          cudaStream_t stream) const;

        /// The shared entry validation for the big-to-small direction; called
        /// by switch_down BEFORE its key switch so a bad input cannot be
        /// key-switched into garbage first, and again by split_embedded for
        /// direct callers.
        void validate_big_input(const Ciphertext<Scheme::CKKS>& input,
                                int active_primes) const;

        HEContext<Scheme::CKKS> big_;
        HEContext<Scheme::CKKS> small_;

        int n_big_;
        int n_small_;
        int n_power_big_;
        int n_power_small_;
        int k_;
        int k_power_;
        int big_q_size_;
        int small_q_size_;

        std::unique_ptr<Switchkey<Scheme::CKKS>> swk_down_;
        std::unique_ptr<Switchkey<Scheme::CKKS>> swk_up_;
    };

} // namespace heongpu

#endif // HEONGPU_CKKS_RINGSWITCH_H
